---
- name: Create a Web Stack with one Web Server & DB Server
  hosts: localhost
  connection: local
  vars_files:
    - azure-vars.yaml          

  tasks:
  - name: Creating "{{ web_sg }}" NSG for Web Server
    azure_rm_securitygroup:
      resource_group:  "{{ resource_group }}"
      name: "{{ web_sg }}"
      purge_rules: yes
      state: present
      rules:
        - name: AllowSSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
        - name: AllowMultiPorts
          protocol: Tcp
          destination_port_range: 
            - 80
            - 443
          priority: 101
          access: Allow
          direction: Inbound 

  - name: Creating "{{ db_sg }}" NSG for DB Server
    azure_rm_securitygroup:
      resource_group:  "{{ resource_group }}"
      name: "{{ db_sg }}"
      purge_rules: yes
      state: present
      rules:
        - name: AllowSSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
        - name: AllowMySQL
          protocol: Tcp
          destination_port_range: 
            - 3306
          priority: 101
          access: Allow
          direction: Inbound 

  - name: Create a public IP for "{{ web_server }}"
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      state: present
      name: websrv-public-ip
    register: web_public_ip      


  - name: Create a virtual network interface card for "{{ web_server }}"
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: webnic
      state: present
      virtual_network: "{{ az_vn }}"
      subnet: "{{ az_vn_subnet }}"
      security_group: "{{ web_sg }}"    
      ip_configurations:
        - name: ipconfig01
          public_ip_address_name: websrv-public-ip
          primary: True          
                    

  - name: Create a virtual network interface card for "{{ db_server }}"
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: dbnic
      state: present
      virtual_network: "{{ az_vn }}"
      subnet: "{{ az_vn_subnet }}"
      security_group: "{{ db_sg }}"    
      ip_configurations:
        - name: ipconfig01
          primary: True          


  - name: Create "{{ web_server }}" virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ web_server }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ admin_uname }}"
      admin_password: "{{ admin_passwd }}"
      ssh_password_enabled: True
      os_type: Linux
      short_hostname: "{{ web_server }}"
      state: present
      network_interfaces: webnic
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest


  - name: Collect the public IP          
    debug:
      msg: The Public IP of Web Server "{{ web_server }}" is "{{ web_public_ip.state.ip_address }}"        


  - name: Create "{{ db_server }}" virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ db_server }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ admin_uname }}"
      admin_password: "{{ admin_passwd }}"
      ssh_password_enabled: True
      os_type: Linux
      short_hostname: "{{ db_server }}"
      state: present
      network_interfaces: dbnic
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest        
